### ISSUE TITLE
jiran config crashes when ~/.jira/config.json not found

### ISSUE THREAD

**Issue by marek-pietrzak-tg** [danielkmariam/jiran#2]
Hi,
I've just installed jiran and when I run `jiran config` for the first time it crashes with the error trace:

```
fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/xxx/.jira/config.json'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Config.detail (/xxx/node_modules/jiran/lib/cli/config.js:37:27)
    at Object.<anonymous> (/xxx/node_modules/jiran/lib/jiran.js:12:54)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

The directory `.jira` was there, only file was missing. The other thing - when I created a file with `touch ~/.jira/config.json` it failed saying 

```
undefined:0

^
SyntaxError: Unexpected end of input
```

**Comment by danielkmariam** [comment]
I have resolved the issue by separating the commands and adding a method in config to check if file exists
1. Add a method in config to check a file exists or not
2. If config file does not exist, users will be prompted wit message and the command to run
3. If config file already exists the users will see all options

**Comment by danielkmariam** [comment]
![screen shot 2016-01-28 at 00 04 32](https://cloud.githubusercontent.com/assets/1897967/12632826/d3c2da76-c552-11e5-8551-d98a5117fd15.png)

**Comment by marek-pietrzak-tg** [comment]
:+1:
